import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import "../styles/global.css";
import Drawer from "@/components/drawer";
import Footer from "@/components/footer";
import HeaderPages from "@/components/headerPages";
import Script from "next/script";
// import "bootstrap/dist/css/bootstrap.min.css";
import CallToAction from "@/components/callToAction";
import ProviderRedux from "@/lib";
import AlertSystem from "@/components/alert";
// import "owl.carousel/dist/assets/owl.carousel.css";
// import "owl.carousel/dist/assets/owl.theme.default.css";

// import customScript from "../../public/js/customScript";

// import Script from "next/script";

// import customScript from "@/js/customScript";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Ms. Pastore Barbershop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Head>
        <meta charSet="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <title>Inicio</title>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link
          rel="shortcut icon"
          href="/images/favicon.ico"
          type="image/x-icon"
        />
        <link rel="apple-touch-icon" href="/images/apple-touch-icon.png" />

        <>
          {/* Latest compiled and minified CSS */}
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossOrigin="anonymous"
          />
          {/* Optional theme */}
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossOrigin="anonymous"
          />
          <Script
            src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            strategy="beforeInteractive"
          />

          <Script
            src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
            strategy="afterInteractive"
          />
          <Script src="/path/to/all.js" strategy="afterInteractive" />
          <Script
            src="/path/to/responsive-tabs.js"
            strategy="afterInteractive"
          />
          <Script src="/path/to/custom.js" strategy="afterInteractive" />
          <Script src="/path/to/customScript.js" strategy="afterInteractive" />
          {/* <Script src={all} strategy="afterInteractive"></Script> */}
        </>
      </Head>
      <body className={"barber_version"}>
        {/* <div id="preloader">
          <div className="containerPreloader">
            <div className="spinner">
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
              <div></div>
            </div>
            <span className="descPreloader" data-name="Loading">
              Un momento...
            </span>
          </div>
        </div> */}
        <ProviderRedux>
          <div className="wrapper">
            <Drawer />
            <AlertSystem />
            <div
              className="page-content-wrapper"
              style={{
                width: "calc(100% - 285px)",
                display: "flex",
                flexDirection: "column",
                marginLeft: "auto",
              }}
            >
              <a href="#menu-toggle" className="menuopener" id="menu-toggle">
                <i className="fa fa-bars"></i>
              </a>
              <HeaderPages />
              <CallToAction />
              {children}
              <Footer />
            </div>
          </div>
        </ProviderRedux>
      </body>
      {/* <Script src={all}></Script>
      <Script src="/path/to/responsive-tabs.js"></Script>
      <Script src="/path/to/custom.js"></Script> */}
    </html>
  );
}
